// Drift caught here: the public API changing without anybody deciding it
// should.
//
// A compiler cannot catch this. Renaming an exported field, widening a
// parameter, adding a method to an interface somebody else implements — all of
// them compile perfectly inside this module and break every caller outside it.
// The only way to make such a change visible is to write the whole surface down
// and diff it, so that "we shipped a breaking change" is a line in a pull
// request that a human had to approve rather than a discovery made by a user.
//
// api/ovrin.txt is that record, in the format Go uses for its own api/go1.N.txt.
// Two properties are deliberate:
//
//   - Parameter names are dropped. Renaming a parameter is a documentation
//     change, not an API change, and a golden file that churns on cosmetics is
//     a golden file people stop reading. docs_mirror_test.go checks parameter
//     names, where they matter, against the docs that show them.
//   - Lines are sorted globally. Moving a type from one file to another
//     produces a zero-line diff, so the file records the API rather than the
//     file layout.
//
// The surface is read with go/ast rather than reflection or go/types: the test
// must be hermetic and fast, and reflection cannot see an interface's method
// set on a type nobody implements, nor a constant's declared type at all.
//
// This file also holds the two helpers the other two drift tests share —
// parseRootPackage and render — because all three read the same package the
// same way and three copies of that would be its own drift risk.
//
// The tests are in package ovrin rather than ovrin_test: defaults_doc_test.go
// needs to name the Default* constants as the code names them, so that the
// compiler is one of the three things checking the bridge map. Nothing here
// touches unexported state — the package is parsed as source, not reflected on.
package ovrin

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// apiPath is the golden file, relative to the package directory.
const apiPath = "api/ovrin.txt"

// defaultAPIHeader is written only when api/ovrin.txt does not exist. An
// existing file keeps its own header verbatim: the prose there is somebody's
// decision, not this generator's output.
const defaultAPIHeader = `# ovrin public API surface.
#
# One line per exported symbol, struct field and interface method, sorted.
# Generated by ` + "`go test -run TestAPI -update .`" + `; committed so that any change
# to the public API is a visible line in a diff that somebody had to intend.
#
`

var updateAPI = flag.Bool("update", false, "rewrite "+apiPath+" from the source")

func TestAPI(t *testing.T) {
	t.Parallel()

	_, files := parseRootPackage(t)
	got := apiSurface(t, files)

	if *updateAPI {
		writeAPI(t, got)
		t.Logf("wrote %d lines to %s", len(got), apiPath)
		return
	}

	want := readAPI(t)
	added, removed := diffLines(want, got)
	if len(added) == 0 && len(removed) == 0 {
		return
	}

	var b strings.Builder
	fmt.Fprintf(&b, "the public API does not match %s (%d added, %d removed)\n\n",
		apiPath, len(added), len(removed))
	for _, l := range removed {
		fmt.Fprintf(&b, "  - %s\n", l)
	}
	for _, l := range added {
		fmt.Fprintf(&b, "  + %s\n", l)
	}
	b.WriteString("\n(- is in " + apiPath + " but not in the code; + is in the code but not in " + apiPath + ")\n")
	b.WriteString("\nIf this change was intentional, re-run with -update, update the docs,\n")
	b.WriteString("and add a CHANGELOG entry:\n\n")
	b.WriteString("    go test -run TestAPI -update .\n")
	t.Error(b.String())
}

// ---------------------------------------------------------------------------
// The surface
// ---------------------------------------------------------------------------

// apiSurface renders one sorted line per exported symbol, struct field and
// interface method.
func apiSurface(t *testing.T, files []*ast.File) []string {
	t.Helper()

	// Interfaces are indexed first so that an embedded interface can be
	// expanded into the method set a caller actually has to implement.
	ifaces := map[string]*ast.InterfaceType{}
	for _, f := range files {
		for _, d := range f.Decls {
			gd, ok := d.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, s := range gd.Specs {
				ts, ok := s.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if it, ok := ts.Type.(*ast.InterfaceType); ok {
					ifaces[ts.Name.Name] = it
				}
			}
		}
	}

	var lines []string
	add := func(format string, args ...any) {
		lines = append(lines, fmt.Sprintf("pkg ovrin, "+format, args...))
	}

	for _, f := range files {
		for _, d := range f.Decls {
			switch d := d.(type) {
			case *ast.GenDecl:
				switch d.Tok {
				case token.CONST, token.VAR:
					kw := "const"
					if d.Tok == token.VAR {
						kw = "var"
					}
					// A const spec with neither type nor value repeats the
					// previous one (the iota idiom), so both are carried
					// forward across the block.
					var lastType ast.Expr
					var lastValues []ast.Expr
					for _, s := range d.Specs {
						vs, ok := s.(*ast.ValueSpec)
						if !ok {
							continue
						}
						typ, values := vs.Type, vs.Values
						if typ == nil && len(values) == 0 {
							typ, values = lastType, lastValues
						} else {
							lastType, lastValues = typ, values
						}
						for i, n := range vs.Names {
							if !n.IsExported() {
								continue
							}
							var val ast.Expr
							if i < len(values) {
								val = values[i]
							}
							ty := declaredType(typ, val)
							if ty == "" {
								t.Errorf("%s: cannot infer the type of %s %s; "+
									"extend inferType in api_test.go", apiPath, kw, n.Name)
								ty = "?"
							}
							add("%s %s %s", kw, n.Name, ty)
						}
					}
				case token.TYPE:
					for _, s := range d.Specs {
						ts, ok := s.(*ast.TypeSpec)
						if !ok || !ts.Name.IsExported() {
							continue
						}
						name := ts.Name.Name + renderTypeParams(ts.TypeParams)
						switch u := ts.Type.(type) {
						case *ast.StructType:
							add("type %s struct", name)
							for _, fr := range flattenFields(u.Fields) {
								if !ast.IsExported(fr.name) {
									continue
								}
								add("type %s struct, %s %s", name, fr.name, fr.typ)
							}
						case *ast.InterfaceType:
							add("type %s interface", name)
							for _, m := range interfaceMethods(u, ifaces, map[string]bool{}) {
								if !ast.IsExported(m.name) {
									continue
								}
								add("type %s interface, %s%s", name, m.name, m.sig)
							}
						case *ast.FuncType:
							add("type %s func%s", name, signature(u))
						default:
							add("type %s %s", name, render(ts.Type))
						}
					}
				}
			case *ast.FuncDecl:
				if !d.Name.IsExported() {
					continue
				}
				if d.Recv == nil {
					add("func %s%s%s", d.Name.Name, renderTypeParams(d.Type.TypeParams), signature(d.Type))
					continue
				}
				// A method on an unexported type is not part of the surface,
				// even when the method itself is exported.
				if !ast.IsExported(baseTypeName(d.Recv.List[0].Type)) {
					continue
				}
				add("method (%s) %s%s", render(d.Recv.List[0].Type), d.Name.Name, signature(d.Type))
			}
		}
	}

	sort.Strings(lines)
	return lines
}

// declaredType renders a const or var's type: the written one if there is one,
// otherwise inferred from the value.
func declaredType(typ, val ast.Expr) string {
	if typ != nil {
		return render(typ)
	}
	return inferType(val)
}

// inferType names the type of a value expression without type checking.
//
// go/types would do this properly, but it needs an importer, which means either
// reading the build cache or compiling the standard library from source — the
// first is not hermetic and the second is not fast. The cases below cover every
// untyped declaration in this package; an unhandled one fails the test by name
// rather than emitting a wrong line, so the fix is always to add a case here.
func inferType(val ast.Expr) string {
	switch v := val.(type) {
	case *ast.BasicLit:
		switch v.Kind {
		case token.INT:
			return "int"
		case token.FLOAT:
			return "float64"
		case token.IMAG:
			return "complex128"
		case token.CHAR:
			return "rune"
		case token.STRING:
			return "string"
		}
	case *ast.Ident:
		switch v.Name {
		case "true", "false":
			return "bool"
		case "iota":
			return "int"
		}
	case *ast.BinaryExpr:
		// 64 << 20, 1 + iota: an untyped constant expression takes the type of
		// its operands, and mixing kinds would not compile.
		if s := inferType(v.X); s != "" {
			return s
		}
		return inferType(v.Y)
	case *ast.ParenExpr:
		return inferType(v.X)
	case *ast.UnaryExpr:
		if cl, ok := v.X.(*ast.CompositeLit); ok && v.Op == token.AND {
			return "*" + render(cl.Type)
		}
		return inferType(v.X)
	case *ast.CompositeLit:
		return render(v.Type)
	case *ast.CallExpr:
		switch fn := v.Fun.(type) {
		case *ast.Ident:
			// A conversion to a package type: Kind("pdf").
			return fn.Name
		case *ast.SelectorExpr:
			if pkg, ok := fn.X.(*ast.Ident); ok {
				switch pkg.Name + "." + fn.Sel.Name {
				case "errors.New", "fmt.Errorf":
					return "error"
				}
			}
		}
	}
	return ""
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

// renderFset is used only for printing. The nodes printed here were parsed
// against a different file set, which is the point: with no position
// information the printer cannot reproduce the source's line breaks, so
// everything comes out on one line and the output depends on the declaration
// rather than on how it was laid out. It is never mutated, so concurrent
// parallel tests may share it.
var renderFset = token.NewFileSet()

var whitespaceRun = regexp.MustCompile(`[ \t\n]+`)

// render prints an expression as a single normalised line.
func render(x ast.Expr) string {
	if x == nil {
		return ""
	}
	var b strings.Builder
	if err := printer.Fprint(&b, renderFset, x); err != nil {
		return "<unprintable: " + err.Error() + ">"
	}
	return normaliseRendered(b.String())
}

// normaliseRendered collapses whitespace and spells the empty interface "any".
//
// go/printer reproduces whichever the source wrote, so without this a doc
// saying `any` and code saying `interface{}` would read as drift when they are
// the same type.
func normaliseRendered(s string) string {
	s = whitespaceRun.ReplaceAllString(s, " ")
	s = strings.ReplaceAll(s, "interface{ }", "any")
	s = strings.ReplaceAll(s, "interface{}", "any")
	return strings.TrimSpace(s)
}

// signature renders "(params) results" with parameter names dropped, which is
// the api/ovrin.txt convention.
func signature(ft *ast.FuncType) string {
	return "(" + strings.Join(paramTypes(ft.Params), ", ") + ")" + results(ft.Results)
}

// paramTypes flattens a parameter list to one rendered type per parameter, so
// that (page, dpi int) and (page int, dpi int) render identically.
func paramTypes(fl *ast.FieldList) []string {
	var out []string
	if fl == nil {
		return out
	}
	for _, f := range fl.List {
		n := len(f.Names)
		if n == 0 {
			n = 1
		}
		for i := 0; i < n; i++ {
			out = append(out, render(f.Type))
		}
	}
	return out
}

// results renders a result list: nothing, one bare type, or a parenthesised
// list. Result names are dropped along with parameter names.
func results(fl *ast.FieldList) string {
	rs := paramTypes(fl)
	switch len(rs) {
	case 0:
		return ""
	case 1:
		return " " + rs[0]
	default:
		return " (" + strings.Join(rs, ", ") + ")"
	}
}

// renderTypeParams renders "[T any]", or "" for a non-generic declaration.
// Type parameter names are kept: they are named in the result type, so dropping
// them would leave "*Result[T]" referring to nothing.
func renderTypeParams(fl *ast.FieldList) string {
	if fl == nil || len(fl.List) == 0 {
		return ""
	}
	var parts []string
	for _, f := range fl.List {
		var names []string
		for _, n := range f.Names {
			names = append(names, n.Name)
		}
		parts = append(parts, strings.TrimSpace(strings.Join(names, ", ")+" "+render(f.Type)))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// fieldRec is one struct field, flattened out of any grouped declaration.
// pos is where it was declared, so that docs_mirror_test.go can report the
// exact line of a field that has drifted.
type fieldRec struct {
	name string
	typ  string
	tag  string
	pos  token.Pos
}

// flattenFields turns "MinX, MinY float64" into one record per name, so that
// regrouping fields is not drift and reordering them is.
func flattenFields(fl *ast.FieldList) []fieldRec {
	var out []fieldRec
	if fl == nil {
		return out
	}
	for _, f := range fl.List {
		tag := ""
		if f.Tag != nil {
			tag = f.Tag.Value
		}
		typ := render(f.Type)
		if len(f.Names) == 0 {
			out = append(out, fieldRec{name: baseTypeName(f.Type), typ: typ, tag: tag, pos: f.Pos()})
			continue
		}
		for _, n := range f.Names {
			out = append(out, fieldRec{name: n.Name, typ: typ, tag: tag, pos: n.Pos()})
		}
	}
	return out
}

// methodRec is one interface method: its name and its rendered signature.
type methodRec struct {
	name string
	sig  string
}

// interfaceMethods returns an interface's methods with embedded interfaces
// expanded, because the method set is what a caller has to implement and an
// embedded name tells them nothing about that. Sorted, so that reordering the
// declaration is not drift. seen guards against a cycle, which would not
// compile but must not hang the test either.
func interfaceMethods(it *ast.InterfaceType, ifaces map[string]*ast.InterfaceType, seen map[string]bool) []methodRec {
	var out []methodRec
	for _, f := range it.Methods.List {
		if len(f.Names) == 0 {
			// An embedded interface, or a type-set element such as ~string.
			name := baseTypeName(f.Type)
			embedded, ok := ifaces[name]
			if !ok || seen[name] {
				continue
			}
			seen[name] = true
			out = append(out, interfaceMethods(embedded, ifaces, seen)...)
			continue
		}
		ft, ok := f.Type.(*ast.FuncType)
		if !ok {
			continue
		}
		for _, n := range f.Names {
			out = append(out, methodRec{name: n.Name, sig: signature(ft)})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

// baseTypeName strips pointers, generic instantiation and package qualifiers
// down to the identifier a declaration is keyed by.
func baseTypeName(x ast.Expr) string {
	switch t := x.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return baseTypeName(t.X)
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.IndexExpr:
		return baseTypeName(t.X)
	case *ast.IndexListExpr:
		return baseTypeName(t.X)
	case *ast.ParenExpr:
		return baseTypeName(t.X)
	}
	return ""
}

// ---------------------------------------------------------------------------
// Shared: reading the package
// ---------------------------------------------------------------------------

// parseRootPackage parses the root package's non-test sources.
//
// Test files are excluded: TestAPI is an exported symbol in this package, and
// including it would put the harness into the surface it is checking.
func parseRootPackage(t *testing.T) (*token.FileSet, []*ast.File) {
	t.Helper()

	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("reading the package directory: %v", err)
	}
	fset := token.NewFileSet()
	var files []*ast.File
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, name, nil, parser.SkipObjectResolution)
		if err != nil {
			t.Fatalf("parsing %s: %v", name, err)
		}
		files = append(files, f)
	}
	if len(files) == 0 {
		t.Fatal("no non-test .go files found in the package directory")
	}
	return fset, files
}

// ---------------------------------------------------------------------------
// The golden file
// ---------------------------------------------------------------------------

func readAPI(t *testing.T) []string {
	t.Helper()
	b, err := os.ReadFile(apiPath)
	if err != nil {
		t.Fatalf("reading %s: %v (re-run with -update to create it)", apiPath, err)
	}
	var out []string
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimRight(line, "\r")
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	sort.Strings(out)
	return out
}

func writeAPI(t *testing.T, lines []string) {
	t.Helper()

	header := defaultAPIHeader
	if b, err := os.ReadFile(apiPath); err == nil {
		// Keep whatever header the file already carries: the prose there was
		// written deliberately and is not this generator's to rewrite.
		var kept []string
		for _, line := range strings.Split(string(b), "\n") {
			if line != "" && !strings.HasPrefix(line, "#") {
				break
			}
			kept = append(kept, line)
		}
		if len(kept) > 0 {
			header = strings.Join(kept, "\n") + "\n"
		}
	}

	var out strings.Builder
	out.WriteString(header)
	for _, l := range lines {
		out.WriteString(l)
		out.WriteByte('\n')
	}
	if err := os.WriteFile(apiPath, []byte(out.String()), 0o644); err != nil {
		t.Fatalf("writing %s: %v", apiPath, err)
	}
}

// diffLines reports what is in got but not want, and what is in want but not
// got. Both inputs are sorted.
func diffLines(want, got []string) (added, removed []string) {
	inWant := make(map[string]bool, len(want))
	for _, l := range want {
		inWant[l] = true
	}
	inGot := make(map[string]bool, len(got))
	for _, l := range got {
		inGot[l] = true
	}
	for _, l := range got {
		if !inWant[l] {
			added = append(added, l)
		}
	}
	for _, l := range want {
		if !inGot[l] {
			removed = append(removed, l)
		}
	}
	return added, removed
}
