// Command receipt extracts a receipt with a real model.
//
// Everything else in this repository is tested against fakes, which prove the
// pipeline is wired correctly and prove nothing about whether a real provider
// accepts the schema ovrin emits. This is the programme that finds out.
//
//	export OPENAI_API_KEY=…
//	go run ./examples/receipt
//
// The receipt is synthetic — generated by gen.go in this directory — because
// a real one is somebody's shopping and rule §7.6 keeps real personal data out
// of the repository.
package main

import (
	"context"
	"errors"
	"fmt"
	"os"
	"time"

	"github.com/BAGOMBEKA-JOB-DEV/ovrin"
	ovrinskyl "github.com/BAGOMBEKA-JOB-DEV/ovrin/model/skyl"
)

// Receipt is what we want out of the image. The descriptions matter more than
// the field names: they are what the model reads.
type Receipt struct {
	Number   string  `ovrin:"receipt number as printed,required"`
	Vendor   string  `ovrin:"the trading name of the shop,required"`
	Currency string  `ovrin:"currency code,required,enum=UGX|USD|EUR|GBP"`
	Subtotal float64 `ovrin:"subtotal before tax,min=0"`
	Total    float64 `ovrin:"total amount including tax,required,min=0"`
}

func main() {
	key := os.Getenv("OPENAI_API_KEY")
	if key == "" {
		fmt.Fprintln(os.Stderr, "set OPENAI_API_KEY to run this example")
		os.Exit(1)
	}
	model := os.Getenv("OVRIN_MODEL")
	if model == "" {
		model = "gpt-5.2"
	}

	c := ovrin.New(
		ovrin.WithModel(ovrinskyl.OpenAI(key, model)),
		ovrin.WithHook(func(_ context.Context, ev ovrin.Event) {
			if ev.Err != nil {
				fmt.Printf("  %-9s %-8s %v\n", ev.Op, ev.Duration.Round(time.Millisecond), ev.Err)
				return
			}
			fmt.Printf("  %-9s %s\n", ev.Op, ev.Duration.Round(time.Millisecond))
		}),
	)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	fmt.Println("stages")
	res, err := ovrin.Extract[Receipt](ctx, c, ovrin.File("examples/receipt/receipt.png"))
	if err != nil {
		// The interesting failure is a provider rejecting the schema: that is
		// the JSON Schema dialect edge internal/jsonschema warns about, and it
		// is the one thing a fake can never surface.
		if errors.Is(err, ovrin.ErrBadRequest) {
			fmt.Fprintf(os.Stderr, "\nthe provider rejected the request: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "\nextract: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("\n%s — %s %.2f from %s\n",
		res.Data.Number, res.Data.Currency, res.Data.Total, res.Data.Vendor)
	fmt.Printf("confidence %.2f · valid %t · review %t\n\n",
		res.Confidence, res.Valid, res.NeedsReview)

	for _, field := range []string{"number", "vendor", "currency", "subtotal", "total"} {
		e, ok := res.Explain(field)
		if !ok {
			continue
		}
		fmt.Println(e)
	}

	for _, r := range res.Reasons {
		fmt.Printf("review: %s — %s\n", r.Field, r.Why)
	}
}
